b:
		terraform apply -var-file ~/project_infrastructure/0.account_setup/configurations.tfvars --auto-approve
d:
		terraform destroy -var-file ~/project_infrastructure/0.account_setup/configurations.tfvars --auto-approve
